### PR TITLE
New configuration options

### PR DESCRIPTION
**Pull request by jiangjunfeng98**
# 中文：
## 变化：
- 支持“上一步”按钮隐藏
- 支持 exit 事件回调
- 对外暴露 options type 

# English
## change：
- Support "previousButton" hiding
- add “exit” event callback
- export options type

> [From Baidu Translation](https://fanyi.baidu.com/)

I passed the test by demo

### CODE REVIEW

**Comment by jiangjunfeng98** [comment]
image
image

**Comment by jiangjunfeng98** [comment]
I hope it can be merged. I need these functions urgently

**Comment by fatihsolhan** [comment]
Hi @jiangjunfeng98 thanks a lot for your contribution.
This option makes sense, but I think I'd change the option key to something else rather than show since it is already shown by default.

Could be
```
hideButtons?: {
  previous?: boolean
  next?: boolean
}
```
I am on my way to home, if you have another suggestion, please let me know.

**Comment by jiangjunfeng98** [comment]
> Hi @jiangjunfeng98 thanks a lot for your contribution. This option makes sense, but I think I'd change the option key to something else rather than show since it is already shown by default.
> 
> Could be
> 
> ```
> hideButtons?: {
>   previous?: boolean
>   next?: boolean
> }
> ```
> 
> I am on my way to home, if you have another suggestion, please let me know.

Ye，It's a better idea。I look forward to its update

**Comment by jiangjunfeng98** [comment]
> Hi @jiangjunfeng98 thanks a lot for your contribution. This option makes sense, but I think I'd change the option key to something else rather than show since it is already shown by default.
> 
> Could be
> 
> ```
> hideButtons?: {
>   previous?: boolean
>   next?: boolean
> }
> ```
> 
> I am on my way to home, if you have another suggestion, please let me know.

I have changed the hidden property of the option to hideButtons

**Comment by fatihsolhan** [comment]
> > Hi @jiangjunfeng98 thanks a lot for your contribution. This option makes sense, but I think I'd change the option key to something else rather than show since it is already shown by default.
> > Could be
> > ```
> > hideButtons?: {
> >   previous?: boolean
> >   next?: boolean
> > }
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > I am on my way to home, if you have another suggestion, please let me know.
> 
> I have changed the hidden property of the option to hideButtons

Thank you @jiangjunfeng98 

Although this option makes sense, I am sorry to say that I'll need to think a little bit more to merge this configuration option. Because you can already control the visibility of buttons with the custom UI option.

If we merge this, this option will be unused with the custom UI because we are handling the visibility of the button in the custom UI.
If you need this urgently, I would suggest grabbing the default step's HTML code [from here](https://github.com/fatihsolhan/v-onboarding/blob/main/src/components/VOnboardingStep.vue#L8) and using it that way for now.


Please let me know if this helps

**Comment by jiangjunfeng98** [comment]
> from here

thanks。But I think `options` is simpler and cheaper than `Custom UI`.  Developers prefer to achieve the same effect at low cost

**Comment by fatihsolhan** [comment]
Hey @jiangjunfeng98, thanks again for your contribution and your time.
After having some discussions, I decided to merge this PR but couldn't find time to get back here, sorry.
I'll review and merge it as soon as possible

**Comment by fatihsolhan** [comment]
I've added a commit to make `hideButtons` option reactive with computed.

Thanks again for your contribution @jiangjunfeng98, I am merging this to staging now and will release today.

**Pull request merged**
